package:
  name: clasp
  version: "1.0.0"

source:
  git_rev: yitzchak_conda
  git_url: https://github.com/clasp-developers/clasp.git
  git_depth: 0

requirements:
  build:
    - elfutils
    - gmp
    - llvm=14
    - llvmdev=14
    - clang=14
    - fmt
    - boost-cpp
    - git
    - pkg-config
    - ninja
    - sbcl

  run:
    - elfutils
    - gmp
    - llvm=14
    - clang=14
    - fmt
    - boost-cpp

about:
  home: https://github.com/clasp-developers/clasp