package:
  name: clasp
  version: "1.0.0"

source:
  git_rev: yitzchak_conda
  git_url: https://github.com/clasp-developers/clasp.git
  git_depth: 0

requirements:
  build:
    - elfutils
    - libffi
    - gmp
    - ncurses
    - libllvm13
    - libclang13
    - clang =13
    - zlib
    - fmt
    - libnetcdf
    - czmq
    - boost-cpp
    - git
    - pkg-config
    - ninja
    - sbcl

  run:
    - elfutils
    - libffi
    - gmp
    - ncurses
    - libllvm13
    - libclang13
    - clang =13
    - zlib
    - fmt
    - libnetcdf
    - czmq
    - boost-cpp

test:
  imports:
    -

about:
  home: https://github.com/clasp-developers/clasp